#!/usr/bin/env python3
"""
Report Generator - Creates comprehensive reports from workflow executions
Developed by Team 10x.in
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any

# Try to import optional dependencies
try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        Image, PageBreak, ListFlowable, ListItem
    )
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

ROOT_DIR = Path(__file__).resolve().parent.parent.parent.parent.parent


class ReportGenerator:
    """Generates comprehensive reports from workflow executions."""

    def __init__(self, output_dir: str = None):
        self.output_dir = Path(output_dir) if output_dir else ROOT_DIR / "output" / "reports"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_executive_summary(self, workflow: dict) -> str:
        """Generate executive summary report."""
        output_file = self.output_dir / f"executive_summary_{workflow['workflow_id']}.md"

        # Calculate statistics
        total_steps = len(workflow["steps"])
        completed_steps = sum(1 for s in workflow["steps"] if s.get("status") == "completed")
        failed_steps = sum(1 for s in workflow["steps"] if s.get("status") == "failed")
        success_rate = (completed_steps / total_steps * 100) if total_steps > 0 else 0

        # Get execution time
        start_time = workflow.get("execution", {}).get("started_at")
        end_time = workflow.get("execution", {}).get("completed_at")

        if start_time and end_time:
            try:
                start = datetime.fromisoformat(start_time.replace("Z", "+00:00"))
                end = datetime.fromisoformat(end_time.replace("Z", "+00:00"))
                duration = end - start
                duration_str = str(duration)
            except:
                duration_str = "N/A"
        else:
            duration_str = "N/A"

        # Generate summary content
        content = f"""# Executive Summary

## {workflow['name']}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Workflow ID:** {workflow['workflow_id']}

---

## Overview

{workflow['description']}

---

## Key Metrics

| Metric | Value |
|--------|-------|
| Total Steps | {total_steps} |
| Completed | {completed_steps} |
| Failed | {failed_steps} |
| Success Rate | {success_rate:.1f}% |
| Duration | {duration_str} |
| Status | **{workflow['status'].upper()}** |

---

## Steps Summary

"""

        for i, step in enumerate(workflow["steps"], 1):
            status_emoji = "✅" if step.get("status") == "completed" else "❌" if step.get("status") == "failed" else "⏳"
            content += f"{i}. {status_emoji} **{step['name']}** - {step['skill']}\n"

        content += """

---

## User Inputs

"""
        if workflow.get("user_inputs", {}).get("answers"):
            for key, value in workflow["user_inputs"]["answers"].items():
                content += f"- **{key}:** {value}\n"
        else:
            content += "No user inputs recorded.\n"

        content += """

---

## Key Outputs

"""
        # Extract key outputs from completed steps
        for step in workflow["steps"]:
            if step.get("status") == "completed" and step.get("outputs"):
                content += f"### {step['name']}\n\n"
                outputs = step["outputs"]
                if isinstance(outputs, dict):
                    for key, value in list(outputs.items())[:5]:  # Limit to 5 items
                        if isinstance(value, str) and len(value) > 200:
                            value = value[:200] + "..."
                        content += f"- **{key}:** {value}\n"
                content += "\n"

        content += f"""
---

## Recommendations

Based on the workflow execution:

"""
        if success_rate == 100:
            content += "- ✅ All steps completed successfully. Workflow is ready for production use.\n"
        elif success_rate >= 80:
            content += "- ⚠️ Most steps completed. Review failed steps for improvements.\n"
        else:
            content += "- ❌ Significant failures detected. Review and adjust workflow configuration.\n"

        content += """

---

*Report generated by 10x Team Workflow Engine*
*Developed by Team 10x.in | https://10x.in*
"""

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"Executive summary generated: {output_file}")
        return str(output_file)

    def generate_detailed_report(self, workflow: dict) -> str:
        """Generate detailed technical report."""
        output_file = self.output_dir / f"detailed_report_{workflow['workflow_id']}.md"

        content = f"""# Detailed Workflow Report

## {workflow['name']}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Workflow ID:** {workflow['workflow_id']}

---

## Workflow Configuration

```json
{{
  "workflow_id": "{workflow['workflow_id']}",
  "name": "{workflow['name']}",
  "status": "{workflow['status']}",
  "created_at": "{workflow['created_at']}"
}}
```

---

## Description

{workflow['description']}

---

## Execution Timeline

"""
        execution = workflow.get("execution", {})
        content += f"""| Event | Timestamp |
|-------|-----------|
| Created | {workflow.get('created_at', 'N/A')} |
| Started | {execution.get('started_at', 'N/A')} |
| Completed | {execution.get('completed_at', 'N/A')} |

---

## User Inputs

"""
        if workflow.get("user_inputs", {}).get("questions"):
            content += "### Questions Asked\n\n"
            for q in workflow["user_inputs"]["questions"]:
                content += f"- {q.get('question', 'N/A')}\n"
            content += "\n"

        if workflow.get("user_inputs", {}).get("answers"):
            content += "### Answers Provided\n\n"
            content += "| Question | Answer |\n|----------|--------|\n"
            for key, value in workflow["user_inputs"]["answers"].items():
                content += f"| {key} | {value} |\n"
            content += "\n"

        content += """---

## Step-by-Step Analysis

"""
        for i, step in enumerate(workflow["steps"], 1):
            status = step.get("status", "pending")
            status_badge = {
                "completed": "🟢 Completed",
                "failed": "🔴 Failed",
                "in_progress": "🟡 In Progress",
                "pending": "⚪ Pending"
            }.get(status, "⚪ Unknown")

            content += f"""### Step {i}: {step['name']}

**Status:** {status_badge}
**Skill:** `{step['skill']}`
**Action:** `{step.get('action', 'execute')}`

"""
            if step.get("inputs"):
                content += "#### Inputs\n\n```json\n"
                content += json.dumps(step["inputs"], indent=2)
                content += "\n```\n\n"

            if step.get("outputs"):
                content += "#### Outputs\n\n```json\n"
                # Truncate large outputs
                outputs = step["outputs"]
                output_str = json.dumps(outputs, indent=2)
                if len(output_str) > 2000:
                    output_str = output_str[:2000] + "\n... (truncated)"
                content += output_str
                content += "\n```\n\n"

            if step.get("error"):
                content += f"#### Error\n\n```\n{step['error']}\n```\n\n"

            if step.get("duration"):
                content += f"**Duration:** {step['duration']}\n\n"

            content += "---\n\n"

        content += """## Analytics

### Performance Metrics

"""
        total_steps = len(workflow["steps"])
        completed = sum(1 for s in workflow["steps"] if s.get("status") == "completed")
        failed = sum(1 for s in workflow["steps"] if s.get("status") == "failed")

        content += f"""| Metric | Value |
|--------|-------|
| Total Steps | {total_steps} |
| Completed | {completed} ({completed/total_steps*100:.1f}%) |
| Failed | {failed} ({failed/total_steps*100:.1f}%) |
| Pending | {total_steps - completed - failed} |

### Skills Used

"""
        skills = {}
        for step in workflow["steps"]:
            skill = step["skill"]
            skills[skill] = skills.get(skill, 0) + 1

        content += "| Skill | Usage Count |\n|-------|-------------|\n"
        for skill, count in sorted(skills.items(), key=lambda x: -x[1]):
            content += f"| {skill} | {count} |\n"

        content += f"""

---

## Appendix

### Raw Workflow JSON

```json
{json.dumps(workflow, indent=2, default=str)}
```

---

*Report generated by 10x Team Workflow Engine*
*Developed by Team 10x.in | https://10x.in*
"""

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"Detailed report generated: {output_file}")
        return str(output_file)

    def generate_pdf_report(self, workflow: dict) -> str:
        """Generate PDF report."""
        if not HAS_REPORTLAB:
            print("reportlab not installed. Install with: pip install reportlab")
            return None

        output_file = self.output_dir / f"report_{workflow['workflow_id']}.pdf"

        doc = SimpleDocTemplate(
            str(output_file),
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=28,
            spaceAfter=30,
            textColor=colors.HexColor('#1a1a2e'),
            alignment=1  # Center
        )

        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=18,
            spaceAfter=12,
            spaceBefore=20,
            textColor=colors.HexColor('#16213e')
        )

        subheading_style = ParagraphStyle(
            'CustomSubheading',
            parent=styles['Heading3'],
            fontSize=14,
            spaceAfter=8,
            spaceBefore=12,
            textColor=colors.HexColor('#0f3460')
        )

        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=11,
            spaceAfter=8,
            textColor=colors.HexColor('#333333'),
            leading=14
        )

        # Build PDF content
        story = []

        # Title page
        story.append(Spacer(1, 100))
        story.append(Paragraph(workflow["name"], title_style))
        story.append(Spacer(1, 20))
        story.append(Paragraph(f"Workflow Report", styles['Heading2']))
        story.append(Spacer(1, 40))
        story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body_style))
        story.append(Paragraph(f"Workflow ID: {workflow['workflow_id']}", body_style))
        story.append(Paragraph(f"Status: {workflow['status'].upper()}", body_style))
        story.append(PageBreak())

        # Executive Summary
        story.append(Paragraph("Executive Summary", heading_style))
        story.append(Paragraph(workflow["description"], body_style))
        story.append(Spacer(1, 20))

        # Metrics table
        total_steps = len(workflow["steps"])
        completed = sum(1 for s in workflow["steps"] if s.get("status") == "completed")
        failed = sum(1 for s in workflow["steps"] if s.get("status") == "failed")
        success_rate = (completed / total_steps * 100) if total_steps > 0 else 0

        metrics_data = [
            ["Metric", "Value"],
            ["Total Steps", str(total_steps)],
            ["Completed", str(completed)],
            ["Failed", str(failed)],
            ["Success Rate", f"{success_rate:.1f}%"],
            ["Status", workflow['status'].upper()]
        ]

        metrics_table = Table(metrics_data, colWidths=[200, 200])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a1a2e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e0e0e0'))
        ]))

        story.append(metrics_table)
        story.append(Spacer(1, 30))

        # Steps
        story.append(Paragraph("Workflow Steps", heading_style))

        for i, step in enumerate(workflow["steps"], 1):
            status = step.get("status", "pending")
            status_indicator = "✓" if status == "completed" else "✗" if status == "failed" else "○"

            story.append(Paragraph(f"{status_indicator} Step {i}: {step['name']}", subheading_style))
            story.append(Paragraph(f"<b>Skill:</b> {step['skill']}", body_style))
            story.append(Paragraph(f"<b>Status:</b> {status}", body_style))

            if step.get("outputs"):
                output_preview = json.dumps(step["outputs"], indent=2)[:300]
                if len(output_preview) >= 300:
                    output_preview += "..."
                story.append(Paragraph(f"<b>Output Preview:</b>", body_style))
                story.append(Paragraph(f"<font face='Courier' size='9'>{output_preview}</font>", body_style))

            story.append(Spacer(1, 15))

        # Footer
        story.append(PageBreak())
        story.append(Spacer(1, 300))
        story.append(Paragraph("─" * 60, body_style))
        story.append(Paragraph("Developed by Team 10x.in | https://10x.in", body_style))

        # Build PDF
        doc.build(story)
        print(f"PDF report generated: {output_file}")
        return str(output_file)

    def generate_analytics_report(self, workflows: List[dict]) -> str:
        """Generate analytics report from multiple workflows."""
        output_file = self.output_dir / f"analytics_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

        # Aggregate statistics
        total_workflows = len(workflows)
        completed_workflows = sum(1 for w in workflows if w["status"] == "completed")
        total_steps = sum(len(w["steps"]) for w in workflows)
        completed_steps = sum(
            sum(1 for s in w["steps"] if s.get("status") == "completed")
            for w in workflows
        )

        # Skill usage analysis
        skill_usage = {}
        for w in workflows:
            for step in w["steps"]:
                skill = step["skill"]
                skill_usage[skill] = skill_usage.get(skill, 0) + 1

        content = f"""# Workflow Analytics Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Analysis Period:** All Time

---

## Overview

| Metric | Value |
|--------|-------|
| Total Workflows | {total_workflows} |
| Completed Workflows | {completed_workflows} ({completed_workflows/total_workflows*100:.1f}%) |
| Total Steps Executed | {total_steps} |
| Successful Steps | {completed_steps} ({completed_steps/total_steps*100:.1f}%) |

---

## Skill Usage Analysis

| Skill | Usage Count | Percentage |
|-------|-------------|------------|
"""
        for skill, count in sorted(skill_usage.items(), key=lambda x: -x[1]):
            percentage = count / total_steps * 100
            content += f"| {skill} | {count} | {percentage:.1f}% |\n"

        content += """

---

## Workflow Performance

| Workflow | Status | Steps | Success Rate |
|----------|--------|-------|--------------|
"""
        for w in workflows:
            steps = len(w["steps"])
            completed = sum(1 for s in w["steps"] if s.get("status") == "completed")
            rate = completed / steps * 100 if steps > 0 else 0
            content += f"| {w['name'][:30]} | {w['status']} | {steps} | {rate:.1f}% |\n"

        content += """

---

## Recommendations

Based on the analytics:

1. **Most Used Skills:** Focus optimization efforts on frequently used skills.
2. **Failure Patterns:** Investigate common failure points in workflows.
3. **Performance:** Monitor step execution times for bottlenecks.

---

*Report generated by 10x Team Workflow Engine*
*Developed by Team 10x.in | https://10x.in*
"""

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"Analytics report generated: {output_file}")
        return str(output_file)

    def generate_all_reports(self, workflow: dict) -> dict:
        """Generate all report types for a workflow."""
        results = {
            "executive_summary": self.generate_executive_summary(workflow),
            "detailed_report": self.generate_detailed_report(workflow),
            "pdf_report": self.generate_pdf_report(workflow)
        }

        return results


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_report.py <workflow_path> [report_type]")
        print("Report types: summary, detailed, pdf, all (default)")
        print("")
        print("Example:")
        print("  python generate_report.py workflow.json all")
        print("  python generate_report.py workflow.json summary")
        sys.exit(1)

    workflow_path = sys.argv[1]
    report_type = sys.argv[2] if len(sys.argv) > 2 else "all"

    if not os.path.exists(workflow_path):
        print(f"Workflow file not found: {workflow_path}")
        sys.exit(1)

    with open(workflow_path, "r") as f:
        workflow = json.load(f)

    generator = ReportGenerator()

    if report_type == "summary":
        result = generator.generate_executive_summary(workflow)
    elif report_type == "detailed":
        result = generator.generate_detailed_report(workflow)
    elif report_type == "pdf":
        result = generator.generate_pdf_report(workflow)
    elif report_type == "all":
        result = generator.generate_all_reports(workflow)
    else:
        print(f"Unknown report type: {report_type}")
        sys.exit(1)

    print("\n--- REPORT GENERATION COMPLETE ---")
    print(json.dumps({"success": True, "reports": result}, indent=2))


if __name__ == "__main__":
    main()
